In [1]:
import numpy as np

In [2]:
def sigmoid(z):
  return 1.0 / (1 + np.exp(-z))

In [3]:
def sigmoid_prime(z):
    return sigmoid(z) * (1-sigmoid(z))

In [4]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [5]:
def initialized_network(input_size: int, hidden_layers: list, output_size: int):
    layers = [input_size] + hidden_layers + [output_size]
    weights = []
    biases = []
    print(f' initialize_network {layers=}')
    
    l = len(layers) - 1

    for i in range(l):
        
        weight = np.random.uniform(-1, 1, (layers[i], layers[i+1]))
        bias = np.random.uniform(-1, 1, (layers[i+1],))
        print(f' #{i+1}/{l} {weight=}')
        print(f'   {bias=}\n')
        weights.append(weight)
        biases.append(bias)

    return weights, biases
        

In [6]:
weights, biases = initialized_network(2,[2,2,2],2)

 initialize_network layers=[2, 2, 2, 2, 2]
 #1/4 weight=array([[ 0.39932464, -0.89748946],
       [-0.24750003, -0.13578477]])
   bias=array([-0.83044915,  0.26025243])

 #2/4 weight=array([[-0.12223255, -0.91057739],
       [-0.92643605, -0.67765512]])
   bias=array([-0.43541724,  0.70108038])

 #3/4 weight=array([[-0.18163872,  0.97514029],
       [-0.04650785, -0.34437053]])
   bias=array([ 0.99514354, -0.49898762])

 #4/4 weight=array([[ 0.63086147,  0.8648835 ],
       [-0.45486898,  0.83209314]])
   bias=array([0.28172552, 0.07365635])



In [7]:
def train_network(td, w, b, lr=0.1, e=1000):
    for epoch in range(e):
        total_error = 0
        for input_val, expected_output in td:
            total_error += train_once(input_val, expected_output, lr, w, b)
        if epoch % 1000 ==0:
            print(f"Epoch {epoch}, Total Error: {total_error}")

    return w, b
            

In [8]:
training_data_0_0 = [
    (
        (0.5,0.5),
        (1,1),
    ),
    (
        (0.5,0.5),
        (1,1),
    )
]

In [9]:
def forward_pass(input_data, weights, biases):
    activations = [input_data]
    for i in range(len(weights)):
        # on error: likely due to the input shape not matching the input nodes.
        input_data = np.dot(input_data, weights[i]) + biases[i]
        input_data = sigmoid(input_data)
        activations.append(input_data)
    return activations

In [10]:
def train_once(input_val, expected_output, learning_rate, weights, biases):
    """
    # Example of adjusting training data to include negative example flag
    training_data = [
        # Positive examples: ((input_features), (target_output, False))
        ((input_features_for_example_1), (target_output_for_example_1, False)),
        # Negative examples: ((input_features), (target_output, True))
        ((input_features_for_negative_example_1), (target_output_for_negative_example_1, True)),
    ]

    """
    # Forward pass: Store activations for each layer
    activations = forward_pass(input_val, weights, biases)

    # Backward pass
    # Calculate output error
    output_error = expected_output - activations[-1]
    total_error = np.sum(output_error ** 2)

    # Calculate gradient for output layer
    d_error = output_error * sigmoid_derivative(activations[-1])

    for i in reversed(range(len(weights))):
        # Calculate error for the current layer
        d_weights = np.outer(activations[i], d_error)
        d_biases = d_error

        # Update weights and biases
        weights[i] += learning_rate * d_weights
        # cannot be: `biases[i] += learning_rate * d_biases` due to numpy
        biases[i] = biases[i] + (learning_rate * d_biases)

        # Propagate the error backward
        if i > 0:
            d_error = np.dot(d_error, weights[i].T) * sigmoid_derivative(activations[i])
    return total_error

In [11]:
train_network(training_data_0_0, weights, biases)

Epoch 0, Total Error: 0.40368117641995105


([array([[ 0.39930205, -0.90150283],
         [-0.24752263, -0.13979813]]),
  array([[-0.10972272, -0.91209643],
         [-0.90943296, -0.67972773]]),
  array([[-0.0261719 ,  1.04628185],
         [ 0.22973878, -0.21854887]]),
  array([[1.73380364, 1.73519602],
         [0.15838442, 1.3163862 ]])],
 [array([-0.83049435,  0.2522257 ]),
  array([-0.39632385,  0.69633351]),
  array([ 1.51898517, -0.26031613]),
  array([1.70887269, 1.19307267])])

In [12]:
def dictify(word):
    thedict = {}
    for i, letter in enumerate(word):
        thedict[letter] = (i+1)/len(word)
    return thedict

In [13]:
bits = dictify("catdog")
bits

{'c': 0.16666666666666666,
 'a': 0.3333333333333333,
 't': 0.5,
 'd': 0.6666666666666666,
 'o': 0.8333333333333334,
 'g': 1.0}

In [14]:
tds = [
    (
        (0.16666666666666666,0.3333333333333333, 0.5),
        (0.6666666666666666,0.8333333333333334, 1.0),
    ),
    (
        (0.6666666666666666,0.8333333333333334, 1.0),
        (0.16666666666666666,0.3333333333333333, 0.5),
    )
]

In [48]:
ws, bs = initialized_network(3,[3],3)
train_network(tds, ws, bs)

 initialize_network layers=[3, 3, 3]
 #1/2 weight=array([[ 0.42212036,  0.75979053, -0.17558092],
       [ 0.54646904,  0.50469965, -0.54428266],
       [ 0.99687195, -0.09400343,  0.8966961 ]])
   bias=array([ 0.1278994 , -0.20424399,  0.62679154])

 #2/2 weight=array([[-0.95865187, -0.1424329 ,  0.71937699],
       [ 0.0557682 ,  0.02253462, -0.71143145],
       [-0.47856375, -0.12111137, -0.05012506]])
   bias=array([ 0.57000853,  0.37961193, -0.56608954])

Epoch 0, Total Error: 0.6232657658157624


([array([[ 0.56357988,  1.24428272, -0.24766042],
         [ 0.63983016,  0.91010253, -0.60688321],
         [ 1.04213467,  0.23231014,  0.84357451]]),
  array([[-1.38069566, -0.61444913,  0.77274615],
         [-0.59223278, -0.68991291, -1.00041395],
         [-0.15987614,  0.21220113,  0.65575977]])],
 [array([-0.16069101, -0.67877984,  0.68366529]),
  array([1.16406198, 1.00662597, 0.55869607])])

In [16]:
cat_numbers = (bits["c"], bits["a"], bits["t"])
fp = forward_pass(cat_numbers, ws, bs)
stib = {v:k for k,v in bits.items()}
print(f"stib: {stib}")
print(f"fp: {fp}")

stib: {0.16666666666666666: 'c', 0.3333333333333333: 'a', 0.5: 't', 0.6666666666666666: 'd', 0.8333333333333334: 'o', 1.0: 'g'}
fp: [(0.16666666666666666, 0.3333333333333333, 0.5), array([0.43388842, 0.52585939, 0.48831745]), array([0.54577744, 0.74325893, 0.85028089])]


In [46]:
def closest_match(value, values_in, values_out):
    fp = forward_pass(value, ws, bs)
    for i in range(len(ws)):
        value = np.dot(value, ws[i]) + bs[i]
        value = sigmoid(value)
    final_output = fp[0]
    closest_numb = min(values_in.values(), key=lambda x: abs(x - final_output))
    predicted_letter = values_out[closest_numb]
    return predicted_letter

In [40]:
ws

[array([[ 1.76042   , -0.93346325, -1.59480991],
        [ 1.7979681 , -1.68149081, -1.06676862],
        [ 0.40407384, -1.60996749, -1.1966817 ]]),
 array([[-1.87762423, -1.86077829, -1.5763203 ],
        [ 1.75896554,  1.74217246,  2.8844176 ],
        [ 1.63031841,  1.73729409,  2.45091741]])]

In [41]:
weights

[array([[ 0.39930205, -0.90150283],
        [-0.24752263, -0.13979813]]),
 array([[-0.10972272, -0.91209643],
        [-0.90943296, -0.67972773]]),
 array([[-0.0261719 ,  1.04628185],
        [ 0.22973878, -0.21854887]]),
 array([[1.73380364, 1.73519602],
        [0.15838442, 1.3163862 ]])]

In [49]:
closest_match(.5, bits, stib)

't'

In [34]:
for letter in fp[0]:
    print(closest_match(letter, bits, stib))

c
a
t


In [35]:
for letter in fp[2]:
    print(closest_match(letter, bits, stib))

t
d
o


In [26]:
train_network(tds, ws, bs)

Epoch 0, Total Error: 0.002703467206552719


([array([[ 1.76042   , -0.93346325, -1.59480991],
         [ 1.7979681 , -1.68149081, -1.06676862],
         [ 0.40407384, -1.60996749, -1.1966817 ]]),
  array([[-1.87762423, -1.86077829, -1.5763203 ],
         [ 1.75896554,  1.74217246,  2.8844176 ],
         [ 1.63031841,  1.73729409,  2.45091741]])],
 [array([-1.53297568,  2.08625939,  1.62771594]),
  array([-0.66781416,  0.21311568,  0.3799994 ])])

In [36]:
fp

[(0.16666666666666666, 0.3333333333333333, 0.5),
 array([0.43388842, 0.52585939, 0.48831745]),
 array([0.54577744, 0.74325893, 0.85028089])]