In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [2]:
# sygmoid
import numpy as np

def sigmoid(z):
  return 1.0 / (1 + np.exp(-z))

In [3]:
print(sigmoid(0))
print(sigmoid(0.5))
print(sigmoid(1))

0.5
0.6224593312018546
0.7310585786300049


In [4]:
sigmoid(-0.2)

np.float64(0.45016600268752216)

In [5]:
def sigmoid_prime(z):
    return sigmoid(z) * (1-sigmoid(z))

In [6]:
def dictify(word):
    thedict = {}
    for i, letter in enumerate(word):
        thedict[letter] = (i+1)/len(word)
    return thedict

In [7]:
bits = dictify('xwing delta')
bits

{'x': 0.09090909090909091,
 'w': 0.18181818181818182,
 'i': 0.2727272727272727,
 'n': 0.36363636363636365,
 'g': 0.45454545454545453,
 ' ': 0.5454545454545454,
 'd': 0.6363636363636364,
 'e': 0.7272727272727273,
 'l': 0.8181818181818182,
 't': 0.9090909090909091,
 'a': 1.0}

In [8]:
stib = {v:k for k,v in bits.items()}
stib

{0.09090909090909091: 'x',
 0.18181818181818182: 'w',
 0.2727272727272727: 'i',
 0.36363636363636365: 'n',
 0.45454545454545453: 'g',
 0.5454545454545454: ' ',
 0.6363636363636364: 'd',
 0.7272727272727273: 'e',
 0.8181818181818182: 'l',
 0.9090909090909091: 't',
 1.0: 'a'}

In [9]:
training_data = (
    (bits['x'], bits['d']),
    (bits['w'], bits['e']),
    (bits['i'], bits['l']),
    (bits['n'], bits['t']),
    (bits['g'], bits['a']),
)

In [10]:
training_data

((0.09090909090909091, 0.6363636363636364),
 (0.18181818181818182, 0.7272727272727273),
 (0.2727272727272727, 0.8181818181818182),
 (0.36363636363636365, 0.9090909090909091),
 (0.45454545454545453, 1.0))

In [11]:
# initialized weights and biases
input_size = 1
hidden_size = 2
output_size = 1

weights_input_to_hidden = np.random.uniform(-1, 1, (input_size, hidden_size))

In [12]:
weights_input_to_hidden

array([[0.68833643, 0.90106152]])

In [13]:
weights_hidden_to_output = np.random.uniform(-1, 1, (hidden_size, output_size))

In [14]:
weights_hidden_to_output

array([[-0.47705316],
       [-0.07425556]])

In [15]:
bias_hidden = np.random.uniform(-1, 1, (hidden_size))

In [16]:
bias_hidden

array([-0.94283126,  0.9310138 ])

In [17]:
bias_output = np.random.uniform(-1, 1, (output_size))

In [18]:
bias_output

array([-0.40630711])

In [19]:
input_values = np.array([bits['x']])

In [20]:
input_values = np.array([bits['x']])
hidden_layer_input = np.dot(input_values, weights_input_to_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)
final_output_input = np.dot(hidden_layer_output, weights_hidden_to_output) + bias_output
final_output = sigmoid(final_output_input)
closest_num = min(bits.values(), key=lambda x: abs(x - final_output))
predicted_letter = stib.get(closest_num)
predicted_letter

'n'

In [21]:
hidden_layer_input = np.dot(input_values, weights_input_to_hidden) + bias_hidden

In [22]:
hidden_layer_input

array([-0.88025522,  1.01292849])

In [23]:
hidden_layer_output = sigmoid(hidden_layer_input)

In [24]:
hidden_layer_output

array([0.29312489, 0.73359287])

In [25]:
final_output_input = np.dot(hidden_layer_output, weights_hidden_to_output) + bias_output

In [26]:
final_output_input

array([-0.60061661])

In [27]:
final_output = sigmoid(final_output_input)

In [28]:
final_output

array([0.35420264])

In [29]:
closest_num = min(bits.values(), key=lambda x: abs(x - final_output))

In [30]:
closest_num

0.36363636363636365

In [31]:
predicted_letter = stib.get(closest_num)
predicted_letter

'n'

In [32]:
learning_rate = 0.1

def train_the_brain(ecount=100_000):
    output_error = 0
    global weights_input_to_hidden
    global bias_hidden
    global weights_hidden_to_output
    global bias_output
    for epoch in range(ecount):
        if epoch % 50_000 == 0:
            print(epoch, output_error)
        for input_value, output_value in training_data:
            # forward pass
            input_array = np.array([input_value])
            output_array = np.array([output_value])
            
            hidden_layer_input = np.dot(input_array, weights_input_to_hidden) + bias_hidden
            hidden_layer_output = sigmoid(hidden_layer_input)
            
            final_output_input = np.dot(hidden_layer_output, weights_hidden_to_output) + bias_output
            final_output = sigmoid(final_output_input)
    
            # back propegation
            output_error = output_array - final_output
            d_final_output = output_error * sigmoid_prime(final_output)
    
            hidden_layer_error = d_final_output.dot(weights_hidden_to_output.T)
            d_hidden_layer = hidden_layer_error * sigmoid_prime(hidden_layer_output)
    
            # update weights and biasis
            weights_hidden_to_output += np.outer(hidden_layer_output, d_final_output) * learning_rate
            bias_output += d_final_output * learning_rate
    
            weights_input_to_hidden += np.outer(input_array, d_hidden_layer) * learning_rate
            bias_hidden += d_hidden_layer * learning_rate

In [33]:
def predicter(word):
    t=()
    for letter in word:
        v=predict_next_letter(bits[letter])
        t+=(v,)

    return t
    

In [34]:
def predict_next_letter(input_val):
    # Convert input letter to numerical form
    input_val = np.array([input_val])

    # Forward pass
    hidden_layer_input = np.dot(input_val, weights_input_to_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)

    final_output_input = np.dot(hidden_layer_output, weights_hidden_to_output) + bias_output
    final_output = sigmoid(final_output_input)

    # Convert numerical output to closest letter encoding
    closest_num = min(bits.values(), key=lambda x: abs(x - final_output))
    predicted_letter = stib[closest_num]

    return predicted_letter

In [35]:
for i in range(1000):
    expected = "delta"
    result = predicter('xwing')
    result = ''.join(result)
    if result!=expected:
        print(result)
        train_the_brain()
    else:
        break

nnnnn
0 0
50000 [0.03474634]


In [36]:
predicter('xwing')

('d', 'e', 'l', 't', 'a')

In [37]:
input_values

array([0.09090909])

In [38]:
print(f"weights_input_to_hidden: {weights_input_to_hidden}")
print(f"bias_hidden: {bias_hidden}")
print(f"weights_hidden_to_output: {weights_hidden_to_output}")
print(f"bias_output: {bias_output}")

weights_input_to_hidden: [[2.59956508 4.98812615]]
bias_hidden: [-1.53479603 -2.57685992]
weights_hidden_to_output: [[3.25127842]
 [7.52927957]]
bias_output: [-1.02257651]
